---

- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: AWXTEST
    vm_name: testvm
    location: eastus
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
